### ISSUE TITLE
Combining MRtrix3tissue with another MRtrix versions

### ISSUE THREAD

**Issue by mblesac** [3Tissue/MRtrix3Tissue#22]
Hi @thijsdhollander,

I'm using MRtrix3tissue for some projects and the results look great. However, I have a small question: the major part of the processing of the data was done with `MRtrix 3.0_RC3-15-g9494da8d`, is there any problem to combine this processing with `dwi2response` and `ss3t_csd_beta1`? 

Best regards,

Manuel

**Comment by thijsdhollander** [comment]
Hi Manuel,

No, that shouldn't be a problem: "input" from other MRtrix versions (e.g. preprocessed data, _"before"_ `dwi2response` and `ss3t_csd_beta1`) should feed into those MRtrix3Tissue steps without issue, and output of these MRtrix3Tissue steps should work without issue in following post-processing using other MRtrix versions.  If you want to average response functions (e.g. for quantitative analysis, etc..), it's also most convenient to use `responsemean` in MRtrix3Tissue (or any most recent MRtrix version).  This because the older `average_response` trips up over new "header" entries in the response functions (just textual comments in those files, but the old `average_response` can't handle their presence).

So generally: no worries at all, this should all function as intended!  Just make sure to cleanly switch which version is in your PATH variable (and open a new terminal if needed for this to happen) when running either version of course.  For citations later on (or to document in publications for reproducibility), I'd recommend to document both versions; for MRtrix3, cite the paper and for MRtrix3Tissue cite the https://3tissue.github.io URL (i.e. as in the example on https://3tissue.github.io/doc/ss3t-csd.html ).

Let me know if you run into any problems; but I don't anticipate any. 😉 

Cheers,
Thijs
